### ISSUE TITLE
got error messages when evaluation

### ISSUE THREAD

**Issue by swkpku** [karlstratos/anchor#1]
when I run evaluation commmand, I got error messages:

Assertion `seperated_token.size() == 2` failed in hmm.cc line 583: Wrong format for labeled data with seperator "__<label>__": 1

the data format in universal-treebank_v2.0 is like:
In  _   ADP IN  _   45  adpmod  _   _

but the code need a data file with "__<label>__"

**Comment by karlstratos** [comment]
The code uses the string kObservationStateSeperator_ defined in hmm.h to split word from label. So you'll have to either 
1. Change that string in the header file (kObservationStateSeperator_ = [your_separator]), or 
2. Change the data format.

**Comment by swkpku** [comment]
@karlstratos  Thank you for your answers. Could you please give me an example of your data format?
The labelled data format I used is like:
labelled.txt:
A__<label>__DET    record__<label>__NOUN    date__<label>__NOUN    has__<label>__VERB    n't__<label>__ADV    been__<label>__VERB    set__<label>__VERB    .__<label>__.

The unlabelled data format I used is like:
unlabelled.txt:
A    record    date    has    n't    been    set    .

The setup in code is kObservationStateSeperator_ =  __<label>__.

Then I run 
./hmm --output tmp/anchor_extended --data unlabelled.txt --train --unsup anchor --states 12 --extend cap,hyphen,digit,suff1,suff2,suff3 --extweight 0.1
to train the model.

./hmm --output tmp/anchor_extended --data labelled.txt --pred tmp/pred

to evaluate the trained model.

Is the above process correct?

**Comment by karlstratos** [comment]
Seems correct. I added an example (using plain anchor, not feature-augmented anchor).

**Comment by swkpku** [comment]
@karlstratos thank you very much！
